# Source Generated with Decompyle++
# File: ElevatorConstants.pyo (Python 2.0)

ELEVATOR_OPEN_TIME = 2.0
ELEVATOR_CLOSE_TIME = 2.0
ELEVATOR_COUNTDOWN_TIME = 10.0
TOON_BOARD_ELEVATOR_TIME = 1.0
TOON_EXIT_ELEVATOR_TIME = 1.0
