# Source Generated with Decompyle++
# File: MsgTypes.pyo (Python 2.0)

CLIENT_OBJECT_UPDATE_FIELD = 24
CLIENT_OBJECT_UPDATE_FIELD_RESP = 24
CLIENT_OBJECT_DISABLE_RESP = 25
CLIENT_OBJECT_DELETE_RESP = 27
CLIENT_SET_ZONE = 29
CLIENT_SET_SHARD = 31
CLIENT_CREATE_OBJECT_REQUIRED = 34
CLIENT_CREATE_OBJECT_REQUIRED_OTHER = 35
QUIET_ZONE_IGNORED_LIST = [
    CLIENT_CREATE_OBJECT_REQUIRED,
    CLIENT_CREATE_OBJECT_REQUIRED_OTHER]
